; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1_arduino]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
board_build.arduino.upstream_packages = no
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.4
	end2endzone/SoftTimers@^2.1.0
	lennarthennigs/Button2@^2.5.0

build_flags = 
  -D ZIGBEE_MODE_ED
  -D CORE_DEBUG_LEVEL=3

; PARTITION SCHEME:
; https://community.platformio.org/t/board-build-partitions-which-option-is-the-right-one/37201/3
; https://github.com/espressif/arduino-esp32/tree/master/tools/partitions
; https://esp32.jgarrettcorbin.com/
; https://raw.githubusercontent.com/espressif/arduino-esp32/refs/tags/3.3.7/boards.txt
; [...]
; According to https://raw.githubusercontent.com/espressif/arduino-esp32/refs/tags/3.3.7/boards.txt,
; to emulate selecting menu option `Zigbee 4MB with spiffs`, I need to define the following:
;     esp32c6.menu.PartitionScheme.zigbee.build.partitions=zigbee
;     esp32c6.menu.PartitionScheme.zigbee.upload.maximum_size=1310720
; Which maps to the following:
board_build.partitions=zigbee.csv
board_upload.maximum_size=1310720

; https://community.platformio.org/t/how-to-change-partition-scheme-for-esp32/29687/5
; https://community.platformio.org/t/moving-from-arduino-ide-to-platformio-ide/42372/15
; https://community.platformio.org/t/how-to-change-partition-scheme-for-esp32/29687/6
board_build.flash_mode = qio
board_build.f_flash = 80000000L

; ESP32 Core Debug Levels:
; https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level
; https://community.platformio.org/t/how-to-set-up-log-level-to-be-able-to-debug-the-esp32/8278
; Set macro `CORE_DEBUG_LEVEL` to one of the following values:
;   NONE    0
;   ERROR   1
;   WARNING 2
;   INFO    3
;   DEBUG   4
;   VERBOSE 5
; For example:
;   -D CORE_DEBUG_LEVEL=2


; Zigbee Modes:
; https://github.com/espressif/arduino-esp32/blob/3.3.7/boards.txt
;  -D ZIGBEE_MODE_ED
;  -D ZIGBEE_MODE_ZCZR


; ERASE FLASH
; https://docs.platformio.org/en/latest/platforms/espressif32.html#erase-flash
; `pio run --target erase`
