; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
;
; Build:
;   pio run -e nanoesp32_c6              ; Build for nanoESP32-C6
;   pio run -e nanoesp32_c6 -t upload    ; Build and upload
;   pio run -e nanoesp32_c6 -t monitor   ; Serial monitor
; or use the pio widgets in the pioarduino GUI in VSCode

[platformio]
boards_dir = .

[env]
framework = arduino
monitor_speed = 115200
monitor_echo = no
monitor_filters = 
	esp32_exception_decoder
	time
upload_protocol = esptool

; ============================================================================
; nanoESP32-C6 aka. ESP32-C6-WROOM-1-N4 Hardware Build
; https://github.com/wuxx/nanoESP32-C6/blob/master/README_en.md
; https://raw.githubusercontent.com/wuxx/nanoESP32-C6/ec1ea9f216f65787982682930222ccacfdeb77f2/doc/esp32-c6_datasheet_en.pdf
; https://raw.githubusercontent.com/wuxx/nanoESP32-C6/ec1ea9f216f65787982682930222ccacfdeb77f2/doc/esp32-c6_technical_reference_manual_en.pdf
;
; The nanoESP32-C6 board is a board that is based on the ESP32-C6-WROOM-1 board.
; It descriptions seems to match the most with the ESP32-C6-DevKitC-1 board of espressif's devkit boards:
; https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html
;
; The board configuration description that matches the most would be esp32-c6-devkitc-1.json from 
; https://github.com/pioarduino/platform-espressif32/raw/refs/heads/main/boards/esp32-c6-devkitc-1.json
; Its connectivity does not list zigbee.
; ============================================================================
[env:nanoesp32_c6]
platform =
	; pioarduino latest stable release
	;   https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
	; arduino-esp32 core 3.3.2
	;   https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
	; arduino-esp32 core 3.3.7
	https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = nanoesp32_c6

lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.4
	end2endzone/SoftTimers@^2.1.0
	lennarthennigs/Button2@^2.5.0

build_type = release

build_flags =
	; ESP32 Core Debug Levels:
	; https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level
	; https://community.platformio.org/t/how-to-set-up-log-level-to-be-able-to-debug-the-esp32/8278
	; Set macro `CORE_DEBUG_LEVEL` to one of the following values:
	;   0  (NONE   )
	;   1  (ERROR  )
	;   2  (WARNING)
	;   3  (INFO   )
	;   4  (DEBUG  )
	;   5  (VERBOSE)
	-DCORE_DEBUG_LEVEL=3
	; Zigbee Mode
	; https://github.com/espressif/arduino-esp32/blob/3.3.7/boards.txt
	; Possible values are
	;  -D ZIGBEE_MODE_ED
	;  -D ZIGBEE_MODE_ZCZR
	-DUSE_ZIGBEE=1
	-DZIGBEE_MODE_ED
	; Other macros based on Arduino IDE build logs:
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0

; PARTITION SCHEME:
; https://community.platformio.org/t/board-build-partitions-which-option-is-the-right-one/37201/3
; https://github.com/espressif/arduino-esp32/tree/master/tools/partitions
; https://esp32.jgarrettcorbin.com/
; https://raw.githubusercontent.com/espressif/arduino-esp32/refs/tags/3.3.7/boards.txt
; [...]
; Zigbee 4MB with spiffs:
;	Confirmed from the Arduino IDE buid log which contains the following `-DARDUINO_PARTITION_zigbee` and `PartitionScheme=zigbee`.
;	board_build.partitions=zigbee.csv
; Zigbee 8MB with spiffs:
;	Confirmed from the Arduino IDE buid log which contains the following `-DARDUINO_PARTITION_zigbee_8MB` and `PartitionScheme=zigbee_8MB`.
;	board_build.partitions=zigbee_8MB.csv
board_build.partitions=zigbee_8MB.csv

; ERASE FLASH
; https://docs.platformio.org/en/latest/platforms/espressif32.html#erase-flash
; `pio run --target erase`

; Ignore more build libraries
; Does not seems to have an efect on the final binary size.
lib_ignore = Matter
